/**
 * Survey modes — visuals + setup forms + participant profile fields.
 * Keys must match server Survey.mode enum.
 * - suggestKey: main topic (not AI-overwritten).
 * - suggestFieldKeys: fields AI may suggest from the main topic (user can edit).
 */
export const MODES = {
  founder: {
    label: 'Idea Validation',
    participantTagline: 'Optional details, then a short conversation. Not graded.',
    desc: 'Discovery interviews for ideas and early concepts.',
    color: '#5c7a6b',
    light: '#e8f0ec',
    border: '#c5d9cf',
    tags: ['Founders', 'Hypothesis testing', 'WTP signals'],
    suggestKey: 'idea',
    suggestFieldKeys: ['target', 'hypothesis'],
    /** Heading for the two-column card that includes the AI suggest control */
    suggestPairsCardTitle: 'Target user & riskiest assumption',
    paramsIntro:
      'Suggest depth: this card only. Suggest fields: previous card (target & assumption).',
    setupFields: [
      {
        id: 'idea',
        type: 'textarea',
        lbl: 'Your idea',
        ph: "Problem, who it’s for, and what you’re testing…",
        h: 100,
        help: 'Core topic for this study—kept as you write it.',
      },
      {
        id: 'target',
        type: 'text',
        lbl: 'Target user',
        ph: 'e.g. Early-career professionals in tech',
        pair: true,
        help: 'Who you want signal from (role, situation, context).',
      },
      {
        id: 'hypothesis',
        type: 'text',
        lbl: 'Riskiest assumption',
        ph: 'e.g. Users will pay $15/month for this',
        pair: true,
        help: 'The belief that would hurt most if wrong.',
      },
      {
        id: 'custom',
        type: 'textarea',
        lbl: 'What you need to learn',
        ph: 'e.g. Willingness to pay at ~$10, main alternatives…',
        opt: true,
        h: 72,
        help: 'Intents to cover—Candor elicits these in conversation, not as a word-for-word list. Optional.',
      },
    ],
    profileFields: [
      { key: 'role', lbl: 'What do you do for work?', ph: 'e.g. Engineer, PM, Designer' },
      { key: 'experience', lbl: 'Years of experience', ph: 'e.g. 2 years' },
      { key: 'industry', lbl: 'Industry', ph: 'e.g. Tech' },
    ],
  },
  researcher: {
    label: 'Academic Research',
    participantTagline: 'Confidential responses for this study only.',
    desc: 'Structured qualitative interviews and neutral prompting.',
    color: '#4a6580',
    light: '#e6eef5',
    border: '#bdd0e0',
    tags: ['Researchers', 'Students', 'Qualitative'],
    suggestKey: 'rq',
    suggestFieldKeys: ['hypothesis', 'criteria'],
    suggestPairsCardTitle: 'Hypothesis & participant criteria',
    paramsIntro:
      'Suggest depth: this card only. Suggest fields: previous card (pair).',
    setupFields: [
      {
        id: 'rq',
        type: 'textarea',
        lbl: 'Research question',
        ph: 'e.g. How do remote workers set work–life boundaries?',
        h: 80,
        help: 'One clear question the interviews support.',
      },
      {
        id: 'hypothesis',
        type: 'text',
        lbl: 'Hypothesis or expected finding',
        ph: 'e.g. Remote workers struggle to switch off',
        pair: true,
        help: 'Optional lens—not leading questions to participants.',
      },
      {
        id: 'criteria',
        type: 'text',
        lbl: 'Participant criteria',
        ph: 'e.g. Full-time remote, 25–45',
        pair: true,
        help: 'Who the study is meant to represent.',
      },
      {
        id: 'custom',
        type: 'textarea',
        lbl: 'Specific probes to include',
        ph: 'e.g. Notifications, boundary tactics…',
        opt: true,
        h: 72,
        help: 'Must-cover themes (optional).',
      },
    ],
    profileFields: [
      { key: 'occupation', lbl: 'Occupation or study field', ph: 'e.g. Psychology student' },
      { key: 'age', lbl: 'Age range', ph: 'e.g. 25–34' },
      { key: 'education', lbl: 'Highest education level', ph: "e.g. Bachelor's" },
    ],
  },
  product: {
    label: 'Product Feedback',
    participantTagline: 'Quick chat—honest feedback, no login.',
    desc: 'Friction, delight, and behavior around your product.',
    color: '#8b5e6e',
    light: '#f5eaee',
    border: '#dfc0cb',
    tags: ['PMs', 'Feature sentiment', 'Churn signals'],
    suggestKey: 'product',
    suggestFieldKeys: ['focus', 'concern'],
    suggestPairsCardTitle: 'Focus & biggest concern',
    paramsIntro:
      'Suggest depth: this card only. Suggest fields: previous card (pair).',
    setupFields: [
      {
        id: 'product',
        type: 'text',
        lbl: 'Product or feature name',
        ph: 'e.g. Slack, mobile checkout',
        help: 'What participants should have in mind.',
      },
      {
        id: 'focus',
        type: 'text',
        lbl: 'What to focus on',
        ph: 'e.g. Dashboard redesign',
        pair: true,
        help: 'Which part of the experience you want stories about.',
      },
      {
        id: 'concern',
        type: 'text',
        lbl: 'Your biggest concern',
        ph: 'e.g. Drop in daily active use',
        pair: true,
        help: 'Risk you want evidence on.',
      },
      {
        id: 'custom',
        type: 'textarea',
        lbl: 'Specific areas to probe',
        ph: 'e.g. Search, first session…',
        opt: true,
        h: 72,
        help: 'Extra angles (optional).',
      },
    ],
    profileFields: [
      { key: 'role', lbl: 'Your role', ph: 'e.g. PM, Designer' },
      { key: 'usage', lbl: 'How often do you use it?', ph: 'e.g. Daily' },
      { key: 'experience', lbl: 'How long have you used it?', ph: 'e.g. 8 months' },
    ],
  },
  event: {
    label: 'Event Feedback',
    participantTagline: 'A few minutes—fresh impressions.',
    desc: 'Post-event reactions while memory is fresh.',
    color: '#7a5c2e',
    light: '#f5eedd',
    border: '#ddc99a',
    tags: ['Events', 'QR ready', 'Real-time'],
    suggestKey: 'event',
    suggestFieldKeys: ['format', 'goal'],
    suggestPairsCardTitle: 'Format & intended takeaway',
    paramsIntro:
      'Suggest depth: this card only. Suggest fields: previous card (pair).',
    setupFields: [
      {
        id: 'event',
        type: 'text',
        lbl: 'Event or session name',
        ph: 'e.g. Growth Summit 2026, keynote',
        help: 'What attendees think they attended.',
      },
      {
        id: 'format',
        type: 'text',
        lbl: 'Format',
        ph: 'e.g. Half-day workshop, virtual',
        pair: true,
        help: 'How the session ran.',
      },
      {
        id: 'goal',
        type: 'text',
        lbl: 'What you wanted attendees to take away',
        ph: 'e.g. Roadmap clarity',
        pair: true,
        help: 'What “good” would look like after.',
      },
      {
        id: 'custom',
        type: 'textarea',
        lbl: 'Specific things to ask about',
        ph: 'e.g. Keynote, networking…',
        opt: true,
        h: 72,
        help: 'Must-ask angles (optional).',
      },
    ],
    profileFields: [
      { key: 'role', lbl: 'Your role', ph: 'e.g. Product Lead' },
      { key: 'firstTime', lbl: 'First time at this event?', ph: 'e.g. Yes / 3rd year' },
    ],
  },
  hr: {
    label: 'Team Pulse',
    participantTagline: 'Anonymous. No login.',
    desc: 'Deeper than a rating scale.',
    color: '#6b5080',
    light: '#efe9f5',
    border: '#cbb8dd',
    tags: ['HR teams', 'Managers', 'Anonymous'],
    suggestKey: 'team',
    suggestFieldKeys: ['period', 'focus'],
    suggestPairsCardTitle: 'Time period & focus area',
    paramsIntro:
      'Suggest depth: this card only. Suggest fields: previous card (pair).',
    setupFields: [
      {
        id: 'team',
        type: 'text',
        lbl: 'Team or department',
        ph: 'e.g. Product — or company-wide',
        help: 'Who the pulse is about.',
      },
      {
        id: 'period',
        type: 'text',
        lbl: 'Time period',
        ph: 'e.g. This quarter',
        pair: true,
        help: 'Window you mean (e.g. after a change).',
      },
      {
        id: 'focus',
        type: 'text',
        lbl: 'Primary focus area',
        ph: 'e.g. Workload, RTO',
        pair: true,
        help: 'Theme leadership needs signal on.',
      },
      {
        id: 'custom',
        type: 'textarea',
        lbl: 'Specific topics to explore',
        ph: 'e.g. Recognition, safety…',
        opt: true,
        h: 72,
        help: 'Sensitive or must-ask topics (optional).',
      },
    ],
    profileFields: [
      { key: 'tenure', lbl: 'How long in this team/org?', ph: 'e.g. 2 years' },
      { key: 'level', lbl: 'Your level', ph: 'e.g. Mid-level, Manager' },
    ],
  },
  csat: {
    label: 'Customer Satisfaction',
    participantTagline: 'No app—tell us how it went.',
    desc: 'The story behind the score.',
    color: '#3d7575',
    light: '#e4f0f0',
    border: '#b0d0d0',
    tags: ['CSAT', 'Loyalty signals', 'Referral intent'],
    suggestKey: 'business',
    suggestFieldKeys: ['touchpoint', 'concern'],
    suggestPairsCardTitle: 'Interaction & satisfaction question',
    paramsIntro:
      'Suggest depth: this card only. Suggest fields: previous card (pair).',
    setupFields: [
      {
        id: 'business',
        type: 'text',
        lbl: 'Your business or product name',
        ph: 'e.g. Bloom Coffee',
        help: 'How customers know you.',
      },
      {
        id: 'touchpoint',
        type: 'text',
        lbl: 'Specific interaction to evaluate',
        ph: 'e.g. Last purchase, onboarding',
        pair: true,
        help: 'Moment in the journey you care about.',
      },
      {
        id: 'concern',
        type: 'text',
        lbl: 'Your biggest question about satisfaction',
        ph: 'e.g. Will they return?',
        pair: true,
        help: 'What you want qualitative evidence for.',
      },
      {
        id: 'custom',
        type: 'textarea',
        lbl: 'Specific things to probe',
        ph: 'e.g. Delivery, value…',
        opt: true,
        h: 72,
        help: 'Extra prompts (optional).',
      },
    ],
    profileFields: [
      { key: 'product', lbl: 'What did you purchase?', ph: 'e.g. Starter plan' },
      { key: 'frequency', lbl: 'How often do you buy from us?', ph: 'e.g. First time, monthly' },
    ],
  },
};

/** Mode keys in display order */
export const MODE_ORDER = ['founder', 'researcher', 'product', 'event', 'hr', 'csat'];
